services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: financial_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financial_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025"
      - "8026:8025"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/financial_tracker
      - REDIS_URL=redis://redis:6379/0
      - DEV_ENV=true
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  redis_data: