# docker-compose.yml
services:
  # PostgreSQL база даних
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: financial_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d your_db_name"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кешування та черг (опціонально)
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django web додаток
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - media_volume:/app/media
      # - static_volume:/app/static
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/financial_tracker
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"


volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: